#!/usr/bin/perl

use Modern::Perl;
use encoding ':locale';

my $addr_spec = do {
   use Regexp::Grammars;
   qr{
<address>

<token: address>       <local_part> \@ <domain>

<token: local_part>	<.atext>+ (?: \. <.atext>+)*
<token: atext>		\p{Alnum} | [!#\$%&'*+-/=?^_`{|}~]

<token: domain>		<.label> (?: \. <.label> )*
<token: label>		\p{Alpha} (?: (?:<.ALNUM> | -)* <.ALNUM>)?
<token: ALNUM>		\p{Alnum}
   }x;

};


sub addr_host {
    my ($addr) = @_;
    $addr =~ /^ $addr_spec $/x or return undef;
    return $/{address}{domain};
}


local $/ = undef;
my $in = <>;

my @hosts = map { addr_host($_) // '' } split /\n/, $in;

my %count = ();
$count{$_}++ for @hosts;

my @sorted = sort { length $a or $count{$a} <=> $count{$b} } keys %count;

say length $_ ? $_ : 'INVALID', "\t", $count{$_} for @sorted;

